name: Vlamir Santo
description: Casado com a Maira, pai da Clara, desenvolvedor web e mobile, apaixonado por hambúrguer, música e ecoturismo.
meta_description: "Códigos, hamburgueres e bobagens."

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'https://vlamirsanto.github.io/'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://vlamirsanto.github.io/'
author:         'Vlamir Santo'

github: 'https://github.com/vlamirsanto'
facebook: 'https://www.facebook.com/vlamir.santo'
instagram: 'https://www.instagram.com/vlamir_santo'
pinterest: 'https://br.pinterest.com/vlamirs'
linkedin: 'https://www.linkedin.com/in/vlamirsanto'
